MSG1 = "Introdueix l'isbn del llibre: "
MSG2 = "Introdueix el títol del llibre: "
MSG3 = "Introdueix l'autor del llibre: "
MSG4 = "Introdueix l'editorial del llibre: "
MSG5 = "Introdueix la data de publicació del llibre: "
AUX = "Vols continuar introduïnt registres [1.Sí - 2.No] \n"
