NOM = "Introduce un nombre: "
APELLIDO = "Introduce un apellido: "
EDAD = "Introduce una edad: "
DESPLEGABLE = "****MENÚ**** \n\t 1.-tecno1 \n\t 2.-tecno2 \n\t 3.-tecno3 \n Introduce el número de la opción"
ERROR = "EROOR"
TECNOLOGIA = "Introduce la tecnologia en la que estas interesado/a: "
REPETIR = "Introduce un 1 si quieres introducir mas registros: "

ROUTE = "./files/"
HEADER = "ID\t\t\t|\tNom\t\t|\tCognom\t|\tEdat\t|\tInterés\t\t|\n" \
         "--------------------------------------------------------------------- "
EXT = ".csv"
MSG1 = "Introdueix el teu nom: "
MSG2 = "Introdueix el teu cognom: "
MSG3 = "Introdueix la teva edat: "
MSG4 = "Digues de quina tecnologia estás interessat:\n 1. Servidors\n 2. 5G\n 3. BIG DATA\n"
MSG5 = "Vols continuar introduïnt registres [1-Sí / 0-No]: "
MSG6 = "Com s'anomenarà el fitxer: "
INT1 = "Servidors"
INT2 = "5G"
INT3 = "BIG DATA"
