ROUTE = "./files/"
MENU = "\t\t\t\t\tOpcions\n------------------------------------------------- \n1. Crear un fitxer.\n2. Mostrar el contingut d'un fitxer.\n3. Modificar el contingut d'un fitxer.\n4. Sortir.\n------------------------------------------------- "
MSG1 = "Com s'anomenarà el fitxer: "
MSG2 = "Introdueix el nom del fitxer:  "
MSG3 = "Quantes línies vols introduir: "
MSG4 = "Introdueix la informació de la linia "
EXIT = "Saliste del programa <3"
