MSG1 = "Introdueix la data: "
MSG2 = "Introdueix el nom: "
MSG3 = "Introdueix la localització: "
MSG4 = "Introdueix l'espècie: "
MSG5 = "Introdueix la mida: "
MSG6 = "Introdueix les característiques: "
AUX = "Vols continuar introduïnt registres [1.Sí - 2.No] \n"
